# Generated by Django 5.2.10 on 2026-02-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='accepts_file',
        ),
    ]
