# Generated by Django 5.2.10 on 2026-01-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipelineId', models.IntegerField()),
                ('piplineName', models.CharField(max_length=30)),
            ],
        ),
    ]
