# Generated by Django 5.2.10 on 2026-02-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinerun',
            name='input_file',
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='fastq_r1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='fastq_r2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='nanopore',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='sequencing_type',
            field=models.CharField(choices=[('PE', 'Paired-end'), ('LR', 'Long-read'), ('HY', 'Hybrid')], default='PE', max_length=2),
            preserve_default=False,
        ),
    ]
