# Generated by Django 5.2.10 on 2026-02-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_remove_pipelinerun_input_file_pipelinerun_fastq_r1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinerun',
            name='fastq_r1',
        ),
        migrations.RemoveField(
            model_name='pipelinerun',
            name='fastq_r2',
        ),
        migrations.RemoveField(
            model_name='pipelinerun',
            name='nanopore',
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='samplesheet',
            field=models.FileField(blank=True, null=True, upload_to='samplesheets/'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='sequencing_type',
            field=models.CharField(choices=[('PE', 'Paired-end'), ('LR', 'Long-read'), ('HY', 'Hybrid')], default='PE', max_length=2),
        ),
    ]
