# Generated by Django 5.2.10 on 2026-02-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_remove_pipelinerun_fastq_r1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='fastq_r1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='fastq_r2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='nanopore',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
