# Generated by Django 5.2.10 on 2026-02-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_pipelinerun_fastq_r1_pipelinerun_fastq_r2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinerun',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='pipelinerun',
            name='result_dir',
        ),
        migrations.RemoveField(
            model_name='pipelinerun',
            name='sequencing_type',
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='annotation_tool',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='assembler',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='assembly_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='busco_lineage',
            field=models.CharField(blank=True, default='bacteria_odb10', max_length=100),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='save_trimmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='skip_annotation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='skip_busco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='skip_fastp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='skip_fastqc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='skip_nanoplot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='skip_toulligqc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='unicycler_args',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='fastq_r1',
            field=models.FileField(blank=True, null=True, upload_to='fastq/'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='fastq_r2',
            field=models.FileField(blank=True, null=True, upload_to='fastq/'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='nanopore',
            field=models.FileField(blank=True, null=True, upload_to='fastq/'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='work_dir',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
