# Generated by Django 5.2.10 on 2026-02-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0005_remove_pipelinerun_parameters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinerun',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='pipelinerun',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='pipelinerun',
            name='unicycler_args',
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='annotation_tool',
            field=models.CharField(choices=[('prokka', 'Prokka'), ('bakta', 'Bakta'), ('dfast', 'DFAST')], default='prokka', max_length=50),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='assembler',
            field=models.CharField(choices=[('unicycler', 'Unicycler'), ('canu', 'Canu'), ('dragonflye', 'Dragonflye')], default='unicycler', max_length=50),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='assembly_type',
            field=models.CharField(choices=[('short', 'Short reads'), ('long', 'Long reads'), ('hybrid', 'Hybrid')], default='short', max_length=50),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='busco_lineage',
            field=models.CharField(choices=[('bacteria_odb10', 'Bacteria'), ('enterobacterales_odb10', 'Enterobacterales')], default='bacteria_odb10', max_length=100),
        ),
    ]
